import { accountInterface } from "./accounts.type";

export interface documentRequestInterfaceInput {
    resident: string,
    document: string,
    status: string,
    isPaid : boolean,
    price : number,
    templateId?: string,
    templateVersion?: number,
    feeAtRequest?: number,
    
    fullName : string | null,
    contact: string | null,
    address: string | null,
    dateOfBirth: string | null,
    civilStatus: string | null,
    nationality: string | null, 
    occupation: string | null,
    yrsOfResidency: number | null,

    purpose : string | null,
    documentNumber : string | null,
    dateIssued : string | null,
    
    businessName : string | null,
    businessAddress : string | null,
    businessType : string | null,
    businessNature : string | null,

    workStatus: string | null,
    workplace: string | null,
    monthlyIncome: string | null,
    expenseType: string | null,
    householdExpenses: string | null,
    assistanceTo: string | null,
    titleNo: string | null,
    taxDeclarationNo: string | null,
    landArea: string | null,
    treeCount: string | null,
    treeType: string | null,
    age: string | null,
    spouseName: string | null,
    annualIncome: string | null,
    purok: string | null,
    officialsSnapshot?: Record<string, any>,
    requestDate?: string,
    requestTime?: string,
    source?: "online" | "walk-in",
    isArchived?: boolean,
    archivedAt?: Date | string,
    statusHistory?: { status: string; at: Date | string }[],
    checkoutSessionId?: string | null,

}

export interface documentRequestInterface {
    _id: string,
    resident: accountInterface,
    document: string,
    status : string,
    isPaid : boolean,
    price: number,
    templateId?: string,
    templateVersion?: number,
    feeAtRequest?: number,
    
    fullName : string | null,
    contact: string | null,
    address: string | null,
    dateOfBirth: string | null,
    civilStatus: string | null,
    nationality: string | null, 
    occupation: string | null,
    yrsOfResidency: number | null,

    purpose : string | null,
    documentNumber : string | null,
    dateIssued : string | null,
    
    businessName : string | null,
    businessAddress : string | null,
    businessType : string | null,
    businessNature : string | null,

    workStatus: string | null,
    workplace: string | null,
    monthlyIncome: string | null,
    expenseType: string | null,
    householdExpenses: string | null,
    assistanceTo: string | null,
    titleNo: string | null,
    taxDeclarationNo: string | null,
    landArea: string | null,
    treeCount: string | null,
    treeType: string | null,
    age: string | null,
    spouseName: string | null,
    annualIncome: string | null,
    purok: string | null,
    officialsSnapshot?: Record<string, any>,
    requestDate?: string,
    requestTime?: string,
    source?: "online" | "walk-in",
    isArchived?: boolean,
    checkoutSessionId?: string | null,

    archivedAt?: Date | string,
    statusHistory?: { status: string; at: Date | string }[],
}
