server {
    listen 80;
    listen [::]:80;
    server_name bims-rabon-elyu.site;
    server_tokens off;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }

    location / {
        default_type text/plain;
        return 503 "HTTPS is being set up.\n";
    }
}
